# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages


os:
  - linux
  - osx

r:
  - release
  - devel

development:
  mode: auto

jobs:
  exclude:
    - r: devel
      os: osx
